### ISSUE TITLE
`npm init typescript-project` fails

### ISSUE THREAD

**Issue by claasahl** [claasahl/create-typescript-project#1]
`npm init typescript-project` fails with:

```console
$ npm init typescript-project
(node:14736) UnhandledPromiseRejectionWarning: Error: package.json: ENOENT: no such file or directory, open 'C:\Users\claasahl\git\npmjs-test\package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFileSync (C:\Users\claasahl\git\react-select-ts\create-typescript-project\node_modules\jsonfile\index.js:64:22)
    at Object.<anonymous> (C:\Users\claasahl\git\react-select-ts\create-typescript-project\build\index.js:195:36)
    at step (C:\Users\claasahl\git\react-select-ts\create-typescript-project\build\index.js:135:21)
    at Object.next (C:\Users\claasahl\git\react-select-ts\create-typescript-project\build\index.js:72:16)
    at fulfilled (C:\Users\claasahl\git\react-select-ts\create-typescript-project\build\index.js:24:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:14736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch                                                                                                block, or by rejecting a promise which was not handled with .catch(). (rejectio                                                                                               n id: 1)
(node:14736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate th                                                                                               e Node.js process with a non-zero exit code.
```

**Comment by claasahl** [comment]
Works on windows with:

```console
PS C:\Users\Claas> node -v
v10.5.0
PS C:\Users\Claas> npm -v
6.4.1
PS C:\Users\Claas> tsc -v
Version 3.1.1
PS C:\Users\Claas\git\react-select-ts-again\tttt>
```

**Comment by claasahl** [comment]
works on mac with:

```console
Claass-MacBook-Pro:test claas.ahlrichs$ node -v
v8.15.1
Claass-MacBook-Pro:test claas.ahlrichs$ npm -v
6.4.1
Claass-MacBook-Pro:test claas.ahlrichs$ tsc -v
-bash: tsc: command not found
```

**Comment by claasahl** [comment]
could not reproduce issue
