### ISSUE TITLE
Is not working with Windows 10

### ISSUE THREAD

**Issue by MihaiCatan** [claasahl/create-typescript-project#13]
Hi,

I installed it global and run. Got the following error:
```
$ npm init typescript-project
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Environment:
Windows 10
node v12.3.1
npm 6.9.0
gitbash

**Comment by claasahl** [comment]
Hi @MihaiCatan 

Thank you for bringing this to my attention. Your console outputs suggest that you are not seeing outputs like the following:

```
Bootstrapping package.json ... Done
Installing typescript ... Done
Installing prettier / pretty-quick ... Done
Bootstrapping .gitignore ... Done
Bootstrapping 'hello world'-sample ... Done
Staging files ... Done

Happy hacking!
```

Is that correct?

**Comment by claasahl** [comment]
I just pushed out v0.8.0, which updates several dependencies. Perhaps, this does the trick 🤞
